name: Python CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Python
        run: python --version

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Application
        run: python src/app.py
